@WMS.API_HostAddress = https://localhost:7012



POST {{WMS.API_HostAddress}}/api/Resources/Add
Content-Type: application/json

{
  "name": "sssssdasasasssll"
}

###

POST {{WMS.API_HostAddress}}/api/Resources/Archive
Content-Type: application/json

{
  "Id":"1d3c4830-a0dc-464e-a170-e9b23de07dfd"
}

###

POST {{WMS.API_HostAddress}}/api/Resources/Update
Content-Type: application/json

{
  
  "Id":"1d3c4830-a0dc-464e-a170-e9b23de07dfd",
   "name": "aaaddaaasddwwaa"
}

###

POST {{WMS.API_HostAddress}}/api/Resources/Activate
Content-Type: application/json

{
  "Id":"1d3c4830-a0dc-464e-a170-e9b23de07dfd"
}

###

GET {{WMS.API_HostAddress}}/api/Resources/GetById/1d3c4830-a0dc-464e-a170-e9b23de07dfd

###

GET {{WMS.API_HostAddress}}/api/Resources/GetAll?Page=1&PageSize=100

###
